### ISSUE TITLE
WoWup AddOn Popup causes an Bug in der GuildRoster Window

### ISSUE THREAD

**Issue by nalamar** [WowUp/WowUp.Addon#16]
Wowup reuses Assets of InGame Windows and calls a protected function, if you have an popup and opens the GuildRoster

Quote from the Guild Roster Manager-Discord
`ya I am 100% sure this is the problem... wowUp addon takes Blizz's table for static Popups  - you can see them all with /dump StaticPopupDialogs
[17:49]
then adds its own new table entry into it, then calls the table with StaticPopup_Show
[17:49]
The problem is literally so many protected things use these

beren — heute um 17:49 Uhr
ugh. blizz needs to get it's crap together
[17:51]
heh yeah they are aware of the issue

Arkaan (GRM Author) — heute um 17:52 Uhr
Ok so... in wowUp addon - I completely removed the taint - main.lua - comment out just line 57
[17:52]
I just wanted to confirm it was the use of  StaticPopup_Show("WowUp_ShowUpdatesAvailable", nil, nil, data)
[17:53]
so @der_nala - this is the cause of the taint... the solution is for addon dev to just build their own frame rather than re-use in-game asset - it's pretty simple solution`

**Comment by linaori** [comment]
I've moved the issue to the addon repository.

I'm not sure if I understand the issue, according to the documentation this is the recommended way of creating a simple popup as documented here: https://wowwiki-archive.fandom.com/wiki/Creating_simple_pop-up_dialog_boxes

**Comment by nalamar** [comment]
Yeah, this may be the "simple way" to Add a "simple" popup - but it's approved and reproduced by 3 ppl that you get an protected function call error. Maybe there is an Typo in your Code which breaks the function or the "tutorial" is out of date or maybe the Data you add isn't just simple and needs a other Solution ...

**Comment by linaori** [comment]
So how can I reproduce it?

**Comment by Nils89** [comment]
Taint issues are hard to reproduce. But I know that this. An very rarely happens in that case, we can make a quickly fix and a log therm complete fix for that.

**Comment by Nils89** [comment]
Taint issues blaim mostly the wrong addon. For a root cause you need a taint log. This is how to get a taint log:

How do I find a taint.log file to upload?
The taint.log is a World of Warcraft client log file that contains information about actions the interface has been prevented from performing due to taint (i.e. addons). Taint logging is not activated by default, but you can enable it by typing /console taintlog 1 in chat. Once activated, you can find the log in World of Warcraft\Logs\taint.log.

**Comment by linaori** [comment]
I have created a new release with a hotfix suggested by @Nils89, a permanent fix will have to come later.

https://github.com/WowUp/WowUp.Addon/releases/tag/1.0.0
