### ISSUE TITLE
WowUp wants to update ThreatClassic2 with the same version after a Re-Scan

### ISSUE THREAD

**Issue by b-morgan** [WowUp/WowUp.Addon#18]
WowUp 2.3.1 wants to update ThreatClassic2 with the same version multiple times. The easiest way to cause this is to do a Re-Scan. Happens on both Classic Era and Burning Crusade Classic.

If the problem is caused by something ThreatClassic2 has done, then please give me enough information so I can report it to them.

[logs.zip](https://github.com/WowUp/WowUp.Addon/files/6571589/logs.zip)
[main.log](https://github.com/WowUp/WowUp.Addon/files/6571590/main.log)
[renderer.log](https://github.com/WowUp/WowUp.Addon/files/6571591/renderer.log)

**Comment by jliddev** [comment]
This is should move to the wowup repo.
