### ISSUE TITLE
9.1.5 Error 

### ISSUE THREAD

**Issue by jliddev** [WowUp/WowUp.Addon#25]
Running the mouse over the map frame icon causes this.

![image](https://user-images.githubusercontent.com/20467484/140008533-6bde028d-0f6b-4aa3-a665-26fc7d12ed97.png)

**Comment by Nils89** [comment]
That's a lib error. 

There will be a lib update soon 

https://www.curseforge.com/wow/addons/libqtip-1-0/issues/49
