### ISSUE TITLE
Error upon latest update

### ISSUE THREAD

**Issue by rbpaiett** [WowUp/WowUp.Addon#39]
The latest update today triggered this error:

3x WowUp/config.lua:38: attempt to call field 'RegisterCanvasLayoutCategory' (a nil value)
[string "@WowUp/config.lua"]:38: in function `SetUpSettings'
[string "@WowUp/main.lua"]:14: in function <WowUp/main.lua:7>

I hope I'm reporting this in the correct area.

**Comment by linaori** [comment]
Is this wotlk?

**Comment by rbpaiett** [comment]
Yes

**Comment by linaori** [comment]
I've released a new version, can you check if that fixes it for you?

**Comment by rbpaiett** [comment]
Sure thing.

**Comment by rbpaiett** [comment]
Looks like it works!  Thanks much.
