### ISSUE TITLE
Issue Following 11.0.2 Update

### ISSUE THREAD

**Issue by swotam** [WowUp/WowUp.Addon#41]
Experiencing the following after the 11.0.2 update. Issue occurs even if no other addons are loaded.

4x WowUp/main.lua:9: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@WowUp/main.lua"]:9: in function <WowUp/main.lua:7>

Locals:
self = Frame {
}
event = "PLAYER_LOGIN"
(*temporary) = nil
(*temporary) = "wowup_data_addon"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
WOWUP = <table> {
 L = <table> {
 }
}
L = <table> {
 Show a list of all addons to be updated in a chat message = "Show a list of all addons to be updated in a chat message"
 Show a popup with a notification after loading when updates are available = "Show a popup with a notification after loading when updates are available"
 Show a list of all addons to be updated in a popup notification = "Show a list of all addons to be updated in a popup notification"
 Click to open settings = "Click to open settings"
 Notification = "Notification"
 Show a chat message indicating whether or not updates are available = "Show a chat message indicating whether or not updates are available"
 Show Minimap icon = "Show Minimap icon"
 All addons are up-to-date = "All addons are up-to-date"
 You have %d addons to be updated = "You have %d addons to be updated"
 You have %d addon to be updated = "You have %d addon to be updated"
 Data addon is missing = "Data addon is missing"
}

**Comment by linaori** [comment]
I've released a new version: https://github.com/WowUp/WowUp.Addon/releases/tag/1.0.23

Can you check if that fixes the problem for you or if anything new pops up?

**Comment by swotam** [comment]
The issue does not occur with 1.0.23, thanks for the quick response.

**Comment by linaori** [comment]
Glad to hear 😁
