### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by jliddev** [WowUp/WowUp.Addon#8]
Create an action that will build it and push a zip release for classic and retail

**Comment by jliddev** [comment]
test

**Comment by N6REJ** [comment]
take a look @ bigwigs packager.. its amazing.. all I have to do is create and tag and `voila done.

**Comment by linaori** [comment]
First release with the packager: https://github.com/WowUp/WowUp.Addon/releases/tag/1.0.9
